- name: Configuring mongodb Repository 
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Installing {{ COMPONENT }} 
  ansible.builtin.package:
    name: mongodb-org
    state: present