- name: Configuring {{COMPONENT}} Repository 
  ansible.builtin.copy:
    src: {{COMPONENT}}.repo
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Installing {{ COMPONENT }} 
  ansible.builtin.package:
    name: {{COMPONENT}}-org
    state: present