- name: Configuring ${COMPONENT} Repository
  ansible.builtin.copy:
    src: ${COMPONENT}.repo
    dest: /etc/yum.repos.d/${COMPONENT}.repo
  
- name: Installing {{ COMPONENT }} 
  ansible.builtin.package:
    name: ${COMPONENT}-org
    state: present

- name: Updating the ${COMPONENT} config to be pblic
  ansible.builtin.replace:
    path: /etc/${DB}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Stating ${COMPONENT} 
  ansible.builtin.systemd:
    name: ${DB}
    state: started
    enabled: true

- name: Download and Extract the component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/${COMPONENT}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Injecting the ${COMPONENT} catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/${COMPONENT}-mains/catalogue.js"
    idempotent: yes

- name: Injecting the ${COMPONENT} catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/${COMPONENT}-mains/users.js"
    idempotent: yes

