- name: Demonstrate User ID
  hosts: all
  become: yes 
  tasks:
    - name: Checking the used ID
      ansible.builtin.shell: id
      register: OUT

    - name: Print user details 
      ansible.builtin.debug:
       msg: "{{ OUT.stdout }}"

    - name: Demo on Loop
      ansible.builtin.debug:
       msg: "Value is {{ item }}"
      loop:
       - 10
       - 20
       - 30

    - name: Copy from source to destination
      ansible.builtin.copy:
         src: system.txt
         dest: /home/centos/system.txt


    - name: Copy from source to destination template
      ansible.builtin.template:
         src: env.txt
         dest: /home/centos/env.txt