- name: Demonstrate User ID
  hosts: all
  tasks:
    - name: Checking the used ID
      ansible.builtin.shell: id
      register: OUT

    - name: Print user details 
      ansible.builtin.debug:
       msg: "{{ OUT.stdout }}"


