- name: Demonstrate User ID
  hosts: all
  become: yes 
  tasks:
    - name: Checking the used ID
      ansible.builtin.shell: id
      register: OUT

    - name: Print user details 
      ansible.builtin.debug:
       msg: "{{ OUT.stdout }}"

    - name: Demo on Loop
      ansible_builtin_debug:
       msg: "{{ i }}"
      loop:
       - 10
       - 20
       - 30
